variable vpc_id {}
variable my_ip {}
variable web_access_ip {}
variable env_prefix {}
variable image_name {}
variable instance_type {}
variable subnet_id {}
variable avail_zone {}
variable private_subnet_cidr_block {}
